In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype = 'int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[3.0, 8.0, 7.0],[6.0, 5.0, 4.0]])
print(b)

[[3. 8. 7.]
 [6. 5. 4.]]


In [4]:
b.ndim #Get Dimensions

2

In [5]:
b.shape #Get Shape

(2, 3)

In [6]:
b.dtype #Get DATATYPE

dtype('float64')

In [7]:
b.itemsize #Get Item Size in bytes

8

In [8]:
b.size #Total Size

6

In [9]:
b.nbytes #i.e. b.itemsize * b.size

48

In [10]:
b.itemsize * b.size

48