In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


# Access 

In [3]:
#Get a specific element [r, c]

a[1, 5]


13

In [4]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
# Get a specific column
a[:, 3]

array([ 4, 11])

In [6]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [7]:
a[0, 1:-2:2]

array([2, 4])

In [8]:
a[1, 2:5:2]

array([10, 12])

# Modify

In [9]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [10]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [11]:
a[:,2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3D Example

In [12]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# Get specific elements (work outside in)

In [14]:
b[0,1,1]

4

In [15]:
# replace
b[:,1,:] = [[9,9]]

In [16]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [9, 9]]])