In [1]:
import numpy as np

In [2]:
# All Zer0s matrix 
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
np.zeros((2, 3, 3, 2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [6]:
# All oness matrix

In [7]:
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [8]:
# Any othe number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [9]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [10]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [11]:
# Any other number (full like)

np.full_like(a.shape, 5)

array([5, 5])

In [12]:
np.full_like(a, 5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [13]:
# Random Decimal Numbers

np.random.rand(4,2)

array([[0.53204441, 0.79961796],
       [0.65082812, 0.29829013],
       [0.61235799, 0.71175542],
       [0.27487793, 0.864698  ]])

In [14]:
np.random.rand(4,2,3)

array([[[0.38705016, 0.128533  , 0.42994528],
        [0.09280165, 0.69736372, 0.35824476]],

       [[0.41636432, 0.27331647, 0.24426826],
        [0.74103355, 0.10296822, 0.64027532]],

       [[0.00429017, 0.32825418, 0.84834948],
        [0.06950156, 0.46319013, 0.36650018]],

       [[0.58586621, 0.5524433 , 0.2062277 ],
        [0.49765727, 0.44077766, 0.97626064]]])

In [15]:
np.random.random_sample(a.shape)

array([[0.88248905, 0.3227504 , 0.09427421, 0.96419563, 0.53846424,
        0.48817297, 0.05265094],
       [0.74527176, 0.14783295, 0.74035465, 0.95174787, 0.69660056,
        0.88072671, 0.11539355]])

In [16]:
# Random Integer Value

np.random.randint(4,7, size=(3,3))

array([[4, 4, 4],
       [6, 6, 6],
       [5, 5, 4]])

In [17]:
# The identity Matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# Repeat an Array 

arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [19]:
# Repeat an Array 

arr2 = np.array([[1,2,3]])
r2 = np.repeat(arr2, 3, axis=0)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
z = np.zeros((3,3))
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [22]:
output[1:4, 1:4] = z

In [23]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Before copying an Array

In [24]:
a1 = np.array([1,2,3])
b1 = a1.copy()
b1[0] = 100

a1

array([1, 2, 3])

In [25]:
b1

array([100,   2,   3])