In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [3]:
a+2 #adds 2 to each element

array([3, 4, 5, 6])

In [4]:
a += 2
a

array([3, 4, 5, 6])

In [5]:
b = np.array([1, 0, 1, 0])
b

array([1, 0, 1, 0])

In [6]:
a+b

array([4, 4, 6, 6])

In [7]:
a**b

array([3, 1, 5, 1], dtype=int32)

In [8]:
#use sin/cos/tan etc.

np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

# Linear Algebra

In [9]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)

In [10]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [12]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [13]:
c = np.identity(3)

In [14]:
np.linalg.det(c) #determinant

1.0

# Statistics

In [15]:
stats = np.array([[1, 2, 3],[4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.min(stats)

1

In [17]:
np.max(stats)

6

In [18]:
np.min(stats, axis=1)

array([1, 4])

In [19]:
np.min(stats, axis=0)

array([1, 2, 3])

In [20]:
np.sum(stats)

21

In [21]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [22]:
np.sum(stats, axis=1)

array([ 6, 15])